### ISSUE TITLE
github actions not running

### ISSUE THREAD

**Issue by Mbrownshoes** [HakaiInstitute/ssta_images#1]
Daily files updates haven't been running for some time. 
https://github.com/HakaiInstitute/ssta_images/actions/runs/5283108274/jobs/9558915369

@steviewanders I think you suggested this could be due to the virtual environment not installing the correct package versions?

**Comment by steviewanders** [comment]
Seems more like this is the issue https://github.com/SciTools/cartopy/issues/2076

**Comment by steviewanders** [comment]
Setting `environment.yaml` to 

```yaml
name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8.8,<4.0.0
  - cmocean>=2.0,<3.0
  - xarray>=0.21.1,<0.22.0
  - glob2>=0.7,<0.8
  - cartopy==0.21.1
  - netcdf4==1.5.8
```

```shell
/opt/homebrew/Caskroom/miniconda/base/bin/python downloadNC.py                                                   (base) 
Traceback (most recent call last):
  File "/Users/stevevandervalk/code/ssta_images/downloadNC.py", line 31, in <module>
    ftp.retrbinary(f"RETR {fileAnomaly}", f_output.write)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/ftplib.py", line 436, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/ftplib.py", line 393, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/ftplib.py", line 359, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/ftplib.py", line 281, in sendcmd
    return self.getresp()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/ftplib.py", line 254, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 ct5km_ssta_v3.1_20230618.nc: No such file or directory
```

Fixes the import error and produces a file issue which I recall as expected? @Mbrownshoes

**Comment by Mbrownshoes** [comment]
The build still fails and provides a super easy to understand error message 
https://github.com/HakaiInstitute/ssta_images/actions/runs/5316278286/jobs/9625627750

**Comment by steviewanders** [comment]
Ya but we fixed the python issue!

**Comment by steviewanders** [comment]
```NODE_OPTIONS=--openssl-legacy-provider``` seems a common workaround e.g. https://github.com/expo/expo-cli/issues/4619 if you don't want to change anything else. 

Otherwise it seems the issue is the update to Node version removed those SSL libraries so you could specify an older version of node in your Action setup.


```yaml

steps:
- uses: actions/checkout@v3
- uses: actions/setup-node@v3
  with:
    node-version: 18
- run: npm ci
- run: npm test
```

> The node-version input is optional. If not supplied, the node version from PATH will be used. However, it is recommended to always specify Node.js version and don't rely on the system one.

Github Actions using latest Ubuntu `Node.js v18.16.0`.

**Comment by steviewanders** [comment]
https://github.com/HakaiInstitute/ssta_images/commit/46a65bb2c9e3c876f1dc9748028baeb38ad009ff
